server:
  port: 8080
  max-http-header-size: 20000
  tomcat:
    threads:
      max: 200


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 30091998As!
    url: jdbc:postgresql://localhost:5432/search_engine
    username: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariCorePool
      max-lifetime: 0
      connection-timeout: 30000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
#    - url: https://lenta.ru/
#      name: Лента.ру
#    - url: https://skillbox.ru/
#      name: Skillbox
#    - url: http://www.playback.ru/
#      name: PlayBack.Ru
#    - url: https://domrebenka.belzdrav.ru/
#      name: Дом Ребенка
#    - url: https://amurkino.ru/
#      name: Амуркино
    - url: https://sendel.ru/
      name: sendel


connection-settings:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
  referrer: https://www.google.com

morphology-settings:
  russianParticleNames:
    - МЕЖД
    - ПРЕДЛ
    - СОЮЗ
  englishParticlesNames:
    - CONJ
    - PREP
    - ARTICLE
    - INT
    - PART
  notCyrillicLetters: "[^а-я]"
  notLatinLetters: "[^a-z]"
  splitter: "\\s+"
  emptyString: " "
  max-frequency: 500
  formats:
    - .pdf
    - .jpg
    - .docx
    - .doc
    - .JPG
    - .jpeg
    - "#"
    - .PDF
    - .xlsx
    - .DOCX
    - .xls
    - .XLSX
    - .png
    - .PNG
    - .rtf
    - .mp4
    - .rar
    - .sql
    - .yaml
    - .yml