server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 30091998As
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru/
      name: Skillbox
    - url: http://www.playback.ru/
      name: PlayBack.Ru
    - url: https://www.volochek.life/
      name: Volochek.ru
    - url: http://radiomv.ru/
      name: Radimov.ru
    - url: https://ipfran.ru/
      name: Ipfran.ru
    - url: https://dimonvideo.ru/
      name: Dimonvideo.ru
    - url: https://nikoartgallery.com/
      name: Nikoartgallery.com
    - url: https://et-cetera.ru/mobile/
      name: Et-cetera.ru
    - url: https://www.lutherancathedral.ru/
      name: Lutherancathedral.ru
    - url: https://dombulgakova.ru/
      name: Dombulgakova.ru

connection-settings:
  user-agent: VanguardSearchBot
  referrer: http://www.google.com
