server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 30091998As
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://lenta.ru/
      name: Лента.ру
    - url: https://skillbox.ru/
      name: Skillbox
    - url: http://www.playback.ru/
      name: PlayBack.Ru
    - url: https://www.volochek.life/
      name: Volochek.ru
    - url: http://radiomv.ru/
      name: Radimov.ru
    - url: https://ipfran.ru/
      name: Ipfran.ru
    - url: https://dimonvideo.ru/
      name: Dimonvideo.ru
    - url: https://et-cetera.ru/mobile/
      name: Et-cetera.ru
    - url: https://www.lutherancathedral.ru/
      name: Lutherancathedral.ru
    - url: https://dombulgakova.ru/
      name: Dombulgakova.ru

connection-settings:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
  referrer: http://www.google.com
