server:
  port: 8080
  max-http-header-size: 20000
  tomcat:
    threads:
      max: 200


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 30091998As!
    url: jdbc:postgresql://localhost:5432/search_engine
    username: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      idle-timeout: 600000
      maximum-pool-size: 30
      auto-commit: true
      pool-name: HikariCorePool
      max-lifetime: 3600000
      connection-timeout: 300000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://lenta.ru/
      name: Лента.ру
    - url: https://skillbox.ru/
      name: Skillbox
    - url: http://www.playback.ru/
      name: PlayBack.Ru

connection-settings:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  referrer: https://www.google.com

morphology-settings:
  russianParticleNames:
    - МЕЖД
    - ПРЕДЛ
    - СОЮЗ
  englishParticlesNames:
    - CONJ
    - PREP
    - ARTICLE
    - INT
    - PART
  notCyrillicLetters: "[^а-я]"
  notLatinLetters: "[^a-z]"
  splitter: "\\s+"
  emptyString: " "
  formats:
    - .pdf
    - .jpg
    - .docx
    - .doc
    - .JPG
    - .jpeg
    - "#"