version: '3.8'

services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - SERVER_PORT=8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/search_engine
    depends_on:
      - service-db
    networks:
      - search-engine

  service-db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-30091998As!}
    ports:
      - "15432:5432"
    volumes:
      - pgadmin-data:/var/lib/postgresql/data
    networks:
      - search-engine

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - search-engine

volumes:
  pgadmin-data:

networks:
  search-engine: