services:

  postgres:
    container_name: search_engine_postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: search_engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./src/main/resources/init-scripts/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    ports:
      - 5432:5432


    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d search_engine" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  search-engine-data:
  pgadmin-data:

networks:
  postgres: